name: benchmark

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  benchmark_implementations:
    name: Run all benchmarks on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - if: matrix.os == 'windows-latest'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
          echo "CMAKE_ARGS=-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_Fortran_COMPILER=gfortran" >> $GITHUB_ENV

      - if: matrix.os == 'windows-latest'
        run: echo "CMAKE_ARGS=\"-DCMAKE_MAKE_PROGRAM=D:/a/_temp/msys64/mingw64/bin/ninja.exe\" CMAKE_PROGRAM_PATH=\"D:/a/_temp/msys64/usr/bin\" CMAKE_GENERATOR=\"Ninja\"" >> $GITHUB_ENV
      
      - if: matrix.os == 'macos-15'
        run: brew reinstall gcc

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: pip install --verbose -e .[benchmarks]
      - run: pip install -e benchmarks/models/NCAR/
      - run: python benchmarks/main.py