name: benchmark

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  benchmark_implementations:
    name: Run all benchmarks on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15]
    steps:
      - uses: actions/checkout@v6
      
      - if: matrix.os == 'macos-15'
        run: brew reinstall gcc

      - if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get install libblitz0-dev libboost-thread-dev libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-timer-dev libboost-filesystem-dev
          git clone https://github.com/igfuw/libmpdataxx.git
          cd libmpdataxx/libmpdata++
          mkdir build
          cd build
          cmake ..
          sudo make install
          cd ../../../
          rm -rf libmpdataxx

      - if: startsWith(matrix.os, 'macos-')
        run: brew install blitz boost

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install --verbose -e .[benchmarks]
      - run: pip install -e benchmarks/models/NCAR/
      - run: python benchmarks/main.py